###
POST https://localhost:5001/api/jogador/create
Content-Type:  application/json

{
    "Nome" : "pedro",
    "Senha" : "123",
    "Email" : "teste@gmail"
}

### listar todos
GET https://localhost:5001/api/jogador/list

### buscar por id
Get https://localhost:5001/api/jogador/getbyid/1

###Deletar um jogador
DELETE  https://localhost:5001/api/jogador/delete/pedro

###Alterar um jogador
PUT  https://localhost:5001/api/jogador/update
Content-Type: application/json

{
    "Id" : 2,
    "Nome" : "Bolinho alterado",
    "Senha" : "123",
    "Email" : "test@gmail"
}