### Cadastrar Jogador
//Não pode cadastrar E-mail repetido
POST https://localhost:5001/api/jogador/create
Content-Type:  application/json

{
    "Nome" : "joao",
    "Senha" : "1234",
    "Email" : "joao@gmail"
}

### listar todos
GET https://localhost:5001/api/jogador/list

### buscar por id
Get https://localhost:5001/api/jogador/getbyid/1

###Deletar um jogador pelo email
DELETE  https://localhost:5001/api/jogador/delete/joao@gmail

###Alterar um jogador
PUT  https://localhost:5001/api/jogador/update
Content-Type: application/json

{
    "Id" : 1,
    "Nome" : "Bolinho alterado",
    "Senha" : "123",
    "Email" : "test@gmail"
}