
### Cadastrar Questao
POST https://localhost:5001/api/questao/create
Content-Type:  application/json

{
    "Nquestao"    : "2.",
    "Pergunta"     : "Qual a resposta correta?                                                 A-                                                                                          B-                                                                                          C-                                                                                        D-",
    "RespostaC"  : "A",
    "RespostaF1" : "B",
    "RespostaF2" : "C",
    "RespostaF3" : "D",
    "Ponto"           : 1

}

### listar todos
GET https://localhost:5001/api/questao/list

###Deletar um Questao peloNúmero da questão (nQuestão)
DELETE  https://localhost:5001/api/questao/delete/2.

###Alterar Questao {id}
PUT  https://localhost:5001/api/questao/update/
Content-Type: application/json

{
    "Id" : 2,
    "Nquestao" : ".11",
    "Pergunta" : "editado",
    "RespostaC"  : "certa",
    "RespostaF1" : "errada11",
    "RespostaF2" : "errada22",
    "RespostaF3" : "errada33",
    "Ponto"       : 10,
    "jogadorId": 1
}