
### Cadastrar Questao
POST https://localhost:5001/api/questao/create
Content-Type:  application/json

{
    "Nquestao" : "2.",
    "Pergunta"  : "que?",
    "RespostaC"  : "certa",
    "RespostaF1" : "errada1",
    "RespostaF2" : "errada2",
    "RespostaF3" : "errada3",
    "Ponto"       : 2

}

### listar todos
GET https://localhost:5001/api/questao/list

###Deletar um Questao peloNúmero da questão (nQuestão)
DELETE  https://localhost:5001/api/questao/delete/1.

###Alterar Questao {id}
PUT  https://localhost:5001/api/questao/update/
Content-Type: application/json

{
    "Id" : 2,
    "Nquestao" : ".11",
    "Pergunta" : "editado",
    "RespostaC"  : "certa",
    "RespostaF1" : "errada11",
    "RespostaF2" : "errada22",
    "RespostaF3" : "errada33",
    "Ponto"       : 2
